llealloo/audiolink

AudioLink/Scripts/AudioLinkAutoConfigurator.cs
- Made it so the `AudioLinkAutoConfigurator` doesn't destroy itself in prefab edit mode
- Made it so the `AudioLinkAutoConfigurator` doesn't add udon behaviours and other components in prefab edit mode
- Added a button to clean up the prefab in prefab edit mode (getting rid of all the components that can't be in avatar projects)
=> Updated the configurator to be less trigger happy

AudioLink/Scripts/AudioLink.cs, AudioLink/Scripts/AudioLinkAutoConfigurator.cs, AudioLink/Scripts/AudioLinkController.cs, AudioLink/Scripts/AudioReactiveLight.cs, AudioLink/Scripts/AudioReactiveObject.cs, AudioLink/Scripts/AudioReactiveSurface.cs, AudioLink/Scripts/AudioReactiveSurfaceArray.cs, AudioLink/Scripts/GlobalSlider.cs, AudioLink/Shaders/AudioLink.cginc
- Added namespace to all scripts to prevent any conflicts
- Added defines to quickly sample from Bass, Low Mids, High Mids, and Trebles
- Added function to test if Audio Link Texture is available for Non Surface shaders to CGInc `AudioLinkIsAvailableNonSurface()`
=> Added a Namespace to everything and add a few helpful things to CGInclude that I felt were missing

AudioLink/Scripts/AudioLinkMiniPlayer.cs, AudioLink/Scripts/AudioLinkMiniPlayerController.cs, AudioLink/Shaders/AudioLink.cginc
- if defd mini player so it only tries to compile if UDON is available (missed this earlier)
- added support for checking if audio texture is available for surface shaders (I think)
=> Fix compiler errors with Mini Player in Projects without UDON + Surface Shader Texture Availability check

AudioLink/Shaders/AudioLink.cginc
Check discussion in #world-audio-dev.
Also this is a breaking change for anyone using AudioLinkAvailableNonSurface with the name change.
=> Add version detection function. Rename availability function

CHANGELOG.md, Docs/README.md
Please read:
- Changelog is a skeleton and needs to be filled out if we go with it.
- I fixed the major discrepancies in the docs, however:
- A few of the functions in AudioLink.cginc are still not described (such as ALDecodeDataAsFloat)
- The table 'Table for does it make sense to index with?' maybe should be updated, I'm not sure. I'll let Charles look.
=> Add WIP changelog and update discrepancies in Docs

AudioLink/AudioLinkController.prefab, AudioLink/Scripts/AudioLinkController.asset, AudioLink/Scripts/AudioLinkController.cs
- Update controller threshold/crossover sliders for better layout and usability.
- Update threshold sliders to use the proper "Bottom to Top" orientation option.
- Update various RectTransform values to be derived from the existing constraint values for consistency.
- Improve general slider alignment and interaction to allow for easier fine-grain adjustment.
- Improve slider use within CyanEmu.
- Remove extraneous GameObjects related to the threshold/crossover sliders.
- Update controller script to modify the threshold slider anchors for dynamic sizing instead of mathematically remapping the size directly.
- Add background color for crossover sliders to visually indicate where the slider is able to move back to.
=> AudioLinkController: UI Cleanup/QoL

README.md
Hi!
I've made two of my assets AudioLink compatible: An Aurora shader that lights up to music and uses the synced time to show everyone the same visuals, and a tool to bake blendshapes into static meshes and have them react to AudioLink via a shader (intended for instancing many speakers with little overhead on a big stage for example). My README mentions right at the top which assets are compatible, license is CC BY-NC-SA. There might be more in the future :)
I'd be honored to have them mentioned on the official repo!
PS: Feel free to make the name more descriptive, that's just what I called my repo - and sorry for the hunk at the end, GitHub's online editor is weird
=> include PiMaker/VRChatUnityThings into compatible tools

AudioLink/Shaders/AudioLink.shader
Chronotensity pass was using AudioLinkDecodeAsUInt which samples the GrabPass. Instead, it should sample the last frame of the CRT directly, since there is a delta of one frame between those 2 methods. This in turn caused ping-ponging values even when there is no audio (I tested with 0 gain). This fixes flickering with chronotensity.
Also, Charles calculates a value for comparison in that pass dependent on if you want to use filtered output or not, but then he never uses this value. I put the value to use where I believe it was intended, and it looks much better to me.
=> Don't sample the GrabPass in CRT for chronotensity

AudioLink/Shaders/AudioLink.cginc
I decided to let clamping to the correct ranges be up to the user, since adding clamps to these functions would hurt performance for what I don't consider very much benefit.
=> Add functions for sampling DFT easier

Docs/README.md
From the  [0.2.5 changelog](https://github.com/llealloo/vrc-udon-audio-link/blob/7e271dc03ab2d177e4fdd9bf62d1f1113f3b9a7c/CHANGELOG.md#025---june-7th-2021):
- Renamed `ALDecodeDataAsUInt` to `AudioLinkDecodeDataAsUInt`
- Renamed `ALDecodeDataAsSeconds` to `AudioLinkDecodeDataAsSeconds`
Small contribution to start off with. 🎉
=> Update docs to match the rename

AudioLink/Shaders/AudioLink.shader, Docs/README.md
Was an off-by-one error. 
`coordinateLocal.x <= 22` -> `coordinateLocal.x < 24`
=> Fix bug: ALPASS_FILTEREDAUDIOLINK + vec2(7, ...) was always zero

AudioLink/Shaders/AudioLink.cginc
This is a public facing API, and as such should have a header guard, so that modular shaders can include the file wherever necessary without stepping on each other's toes.
As a practical example, adding AudioLink support to LTCGI usually breaks shaders when both are used in combination on one material, since `LTCGI.cginc` also includes `AudioLink.cginc`.
=> Add header guard to AudioLink.cginc

AudioLink/Scripts/AudioLink.cs
Switch from Networking.IsInstanceOwner to Networking.LocalPlayer.isInstanceOwner because the static method is known to be broken.
Addresses #161
=> Update instance owner use to the non-broken one.

AudioLink/Scripts/AudioLink.cs, README.md
Fixed a NullReferenceException that would occur if you have an empty UdonBehaviour when trying to link all sound reactive objects.
=> Fixed NullReferenceException in LinkAll.

AudioLink/Shaders/AudioLink.shader
Before this change, there used to be this warning:
`Shader warning in 'AudioLink/Internal/AudioLink': signed/unsigned mismatch, unsigned assumed at line 334`
Note to reviewer: Please double check my assumption that `lastvalTiming >= 0`.
I'm not entirely sure of the values at `ALPASS_GENERALVU + int2(4, 1)`
=> cleanup warning

AudioLink/AudioLinkController.prefab, AudioLink/Scripts/AudioLink.cs
At a lot of events I've seen the host or DJ change these sliders to be similar to this such that the visuals are more responsive to the music.
Even though users can change these, I think it's worth spending a little time to have good defaults.
Before:
After:
=> Change fade defaults to be more responsive

AudioLink/Shaders/AudioLink.shader
This is used neither in CSharp or the shader.
Seems like CN's additional stuff fit into `_AdvancedTimeProps2` without needing an additional variable.
=> Cleanup unused variable

AudioLink/Scripts/AudioLink.cs
This prevents AudioLink script from crashing when an audioSource is not present, as it might only be assigned during runtime instead of in editor.  
Add a warning to notify users about the missing audioSource in case it was unintentional.
=> Adjust null checks for the audioSource

AudioLink/Scripts/AudioLinkAutoConfigurator.cs
UnityEditor.Experimental.SceneManagement becomes UnityEditor.SceneManagement in Unity 2021.
=> Fix updated Unity 2021 namespace compile error

Packages/com.llealloo.audiolink/Editor/Scripts/AudioLinkImportFix.cs, Packages/com.llealloo.audiolink/Editor/Scripts/AudioLinkShaderCompatabilityUtility.cs, Packages/com.llealloo.audiolink/Editor/Scripts/AudioLinkShaderCompatabilityUtility.cs.meta
A utility to upgrade absolute shader paths pointing to the old path to point to the new path
=> AudioLink Shader Compatability Utility

Docs/README.md
There was some discussion in Shader discord, and I think the docs might use a little bit of a bigger explanation of the feature, as it is really useful!
This is just the initial audiolink values, but very heavily filtered, so they move very smoothly. This feature was added in version 2.5.
This is the most recent 4 Band AudioLink value, but heavily smoothed. This allows you to avoid potentially unwanted jerkiness/strobing when the 4 Band values are changing quickly.
There are 16 smoothing levels offered, starting with the most smoothed at `X: 0`.  The least smoothed is at `X: 15`.
You can get a level 10 smoothed Bass value like this:
```hlsl
return AudioLinkData( ALPASS_FILTEREDAUDIOLINK + int2(10, 0) ).rrrr;
```
This feature was added in version 2.5.
=> Updated Filtered AL Docs

Packages/com.llealloo.audiolink/Runtime/Scripts/YtdlpPlayer.cs
- NEVER prompt the user to download yt-dlp if we are not in the VRC usecase (VRC_SDK_VRCSDK3 is not defined)
- First, check if we can find yt-dlp in the users VRChat directory
- Next, check if we can find yt-dlp on the users PATH
- If none of that works, give up with a warning
Also, no longer force the user out of playmode when yt-dlp couldnt be found. Thats pretty annoying.
I found that the player doesn't actually work on Linux at all, because Unity on Linux doesn't support any of the required formats :( left the non-windows handling in since it might work on OSX.
=> Clean up Ytdlp integration

Packages/com.llealloo.audiolink/Runtime/Scripts/YtdlpPlayer.cs
Changes:
- Add Resolution selection (from a list of options)
- Expose audiosource volume if available, so it's easy to adjust
- Add play/pause/stop buttons
- Allow seeking while paused
- Video preview
- Make VideoPlayer a serialized reference so it doesn't need to be on the same object
=> Yt-dlp: UI/functionality tweaks

AudioLinkSandboxUnityProject/Assets/AudioLinkSandbox/Scripts/AudioLinkExperimentalToggle.cs, Packages/com.llealloo.audiolink.extras/Runtime/Scripts/AudioLinkZone.cs
This allows all scripts in the `AudioLink_LiveScene2` demo scene to compile.
=> Update namespace for sandbox scripts

Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLink.cs
* Reverted the Networking.IsInstanceOwner to VRCPlayerApi.isInstanceOwner, as the Networking one is broken.
* Added a LocalPlayer null check before checking if they're the instance owner.
=> Amended isInstanceOwner check

Packages/com.llealloo.audiolink/Editor/Scripts/AudioLinkAssetManager.cs, Packages/com.llealloo.audiolink/Editor/Scripts/AudioLinkShaderCompatabilityUtility.cs
Brings audiolink menu in line with other community assets, like protv and ltcgi.
=> Move the AudioLink menus under the Tools top-level menu

Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLink.cs, Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLinkController.cs
• Made the AudioLinkController call AudioLinkEnable/Disable instead of toggling the AudioLink GameObject.
• Made readbacks stop if AudioLink is disabled.
• Made InitIDs only initialize IDs when called for the first time.
=> Made Controller call AudioLinkEnable/Disable

Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLink.cs
I noticed that whenever* i exit VRC while on my map with AudioLink, while i have that map's project open**, i get an error in the console:
Apparently during cleaning stuff up the `DisableAudioLink()` method gets called after `audioRenderTexture` becomes null, so an attermpt to set its `updateMode` throws an exception.
This PR fixes it by checking if `audioRenderTexture` is null.
\* sometimes it stops doing that, but works again after project reopen
\** no matter if VRC has been run through the "build and test" or normally through Steam
=> Fixed an error with null reference on VRC exit.

Packages/com.llealloo.audiolink/Runtime/Resources/tex_AutoGainIcon.png.meta, Packages/com.llealloo.audiolink/Runtime/Resources/tex_GainIcon.png.meta, Packages/com.llealloo.audiolink/Runtime/Resources/tex_PowerIcon.png.meta, Packages/com.llealloo.audiolink/Runtime/Resources/tex_ResetIcon.png.meta
Currently, the AudioLink icons import at full resolution, high quality. On PC, this becomes 1024x1024 with BC7 compression, and on Mobile, 1024x1024 with ASTC 4x4. Access to high resolution graphics is convenient for asset authoring, but given the in-game size of the included AudioLink controller, a bit overkill. I propose changing the import settings on these four graphics to the following:
PC: 128, DXT1
Mobile: 32, ASTC 5x5
The logic behind these decisions is as follows:
On PC, I simply got really close to the controller in the editor, and increased the icon resolution until I wasn't able to notice further improvements. Then I bumped it up one more. PC platforms generally have access to more VRAM, and HMDs are becoming higher resolution, so I made a concession on performance for the …
=> Reduce icon texture import size

Packages/com.llealloo.audiolink/Runtime/Shaders/AudioLink.shader
Vertically flips the AudioLink CRT on the Linux Unity Editor (OpenGL 4.0),
Tested with both Windows and Android build targets, on both Editor and build, Windows and Linux (also worked under Wine).
Not tested on MacOS.
=> Update AudioLink.shader for linux editor patch

Packages/com.llealloo.audiolink/Runtime/AudioLinkAvatar.prefab, Packages/com.llealloo.audiolink/Runtime/Scripts/ytdlpPlayer.cs
Fix the video player restarting the media ~3 seconds in by offloading the video player Play action to the `prepareCompleted` event.
Swap to using SerializedProperty for the url and resolution fields.
Simplify a couple ternary conditions.
=> Redundant Media Start Fix

Packages/com.llealloo.audiolink/Runtime/Scripts/ytdlpPlayer.cs
- Improve path search logic to include some standard YTDL (not just yt-dlp) executable names.  
- Add menu option for specifying a precise custom executable location under Tools -> AudioLink -> Select - Custom YTDL Location.  
- Move _localytdlpPath use to windows only as it's an exe specific path.  
- Update LocateExecutable to support intaking a list of possible known ytdl executable names to improve search reliability.  
- Update LocateExecutable to support PATH quirks with certain MSeries Macbooks.
=> Improve handling of search for YTDL executables

AudioLinkWebProject/Assets/Plugins/WebGL/WebALPeer.jslib
Attempts to recover from a invalid `UnlinkAnalyser()` call
=> Try and Catch on Unlink

Packages/com.llealloo.audiolink/Runtime/Scripts/AudioReactiveBlendshapes.asset, Packages/com.llealloo.audiolink/Runtime/Scripts/AudioReactiveBlendshapes.asset.meta, Packages/com.llealloo.audiolink/Runtime/Scripts/AudioReactiveBlendshapes.cs, Packages/com.llealloo.audiolink/Runtime/Scripts/AudioReactiveBlendshapes.cs.meta
A small utility script based off `AudioReactiveLight.cs` for blendshapes, allowing a user to quickly drive blendshapes by specifying their index in an array.
=> Add AudioReactiveBlendshapes.cs and related files

Packages/com.llealloo.audiolink/Editor/Scripts/AudioLinkEditor.cs
Anything beyond 2021.3 supports the ByType API.
Is additional cleanup from #324 changes.
=> Make use of FindObjectsByType consistent. 

Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLinkController.cs
This PR fixes #336
As noted in above issue, this make possible to use AudioLinkController without ThemeColorController, while the theme color can be feed from elsewhere independently.
=> Add null check to themeColorController field in AudioLinkController

Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLink.cs
Audiolink normalizes the DFT by dividing by volume. This includes adjustment to the volume based on the falloff/blend curves.
In standalone, it will search for a valid (active and enabled) AudioListener and assume that is the audioTarget to calculate distance curve value from.
In VRC, it uses the player's head tracking data.
Additionally, some logic was added to make sure that playmode doesn't permanently modify the update mode from what it is set to originally. This is necessary for when a separate CRT wraps the original audiolink CRT (such as what VRSL does).
=> Add audiosource curve support to volume assignment (both falloff and blend)
