llealloo/audiolink

AudioLink/AudioLink Avatar Test.prefab, AudioLink/AudioLink Avatar Test.prefab.meta, AudioLink/Scenes/AudioLink_ExampleScene/Scripts/MirrorToggle.asset, AudioLink/Scripts/AudioLink.asset, AudioLink/Scripts/AudioLinkAutoConfigurator.cs, AudioLink/Scripts/AudioLinkController.asset, AudioLink/Scripts/AudioReactiveLight.asset, AudioLink/Scripts/AudioReactiveObject.asset, AudioLink/Scripts/AudioReactiveSurface.asset, AudioLink/Scripts/AudioReactiveSurfaceArray.asset, AudioLink/Scripts/GlobalSlider.asset
- This add an AudioLink Avatar Test prefab that contains the auto configurator
- Auto Configurator has been cleaned up to contain only the relevant code for avatar projects
=> Added a separate avatar prefab

AudioLink/Materials/mat_AudioLinkAutoCorrView.mat, AudioLink/Materials/mat_AudioLinkDebug.mat, AudioLink/Scenes/AudioLink_ExampleScene.unity, AudioLink/Shaders/AudioLinkAutocorrView.shader, AudioLink/Shaders/AudioLinkDebug.shader
* Add visual debug for ColorChord to debug.
=>  * Remove keyword.

AudioLink/Scripts/AudioLinkAutoConfigurator.cs
=> Moved an ifdef to catch one more compiler error thanks Unity

AudioLink/Scripts/AudioLinkMiniPlayer.cs, AudioLink/Scripts/AudioLinkMiniPlayerController.cs
- Fix for potential deadlock between avpro and vrchat during track loop
- Fix for error retry losing the track start time
- Fix for track scrubber sticking when dragged to end of track
=> Multiple miniplayer bugfixes

AudioLink/Scripts/AudioLink.asset, AudioLink/Scripts/AudioLink.cs, AudioLink/Scripts/AudioLinkController.asset, AudioLink/Scripts/AudioLinkMiniPlayer.asset, AudioLink/Scripts/AudioLinkMiniPlayer.cs, AudioLink/Scripts/AudioLinkMiniPlayerController.asset, AudioLink/Scripts/AudioLinkMiniPlayerController.cs, AudioLink/Scripts/AudioReactiveLight.asset, AudioLink/Scripts/AudioReactiveObject.asset, AudioLink/Scripts/AudioReactiveSurface.asset, AudioLink/Scripts/AudioReactiveSurfaceArray.asset, AudioLink/Scripts/GlobalSlider.asset, AudioLink/Shaders/AudioLink.shader
This allows any audio source to be used
Also exposed some other things such as distance from the local player's head and the spatial blend curve to the shader.
Changes currently being used in this world:
https://vrchat.com/home/world/wrld_152013a4-b692-42df-859d-66bef91baa1c
=> Added Audio Source Vol. normalization

AudioLink/AudioLinkMiniPlayer.prefab, AudioLink/Materials/mat_AudioLinkMiniPlayerScreen.mat, AudioLink/Materials/mat_AudioLinkMiniPlayerScreen.mat.meta, AudioLink/Shaders/AudioLinkMiniPlayerScreen.shader, AudioLink/Shaders/AudioLinkMiniPlayerScreen.shader.meta
Use separate screen shader that can correct for aspect ratio coming from AVPro
=> Correct for aspect ratio

AudioLink/Shaders/AudioLink.cginc, Docs/README.md
* Add notes about time retrieval.
* Make functions in cginc match Docs.
* Clarify data in Chronotensity area.
=> Docs and Utility update.

Docs/README.md
Context: https://discord.com/channels/840894950011043841/842357712707649576/886720097090170982
=> Update docs for ALPASS_CHRONOTENSITY

AudioLink/Shaders/AudioLinkDocs_Demo8.shader
=> Take up CNLohrs suggestion to add my name

AudioLink/Scripts/AudioLink.cs
A bit of an experiment with URP
=> Minimal fix for non-networked usage

AudioLink/Shaders/AudioLink.shader
Left comment describing issue in the code for future code lurkers
=> Fixed vertical uv flip of audio texture on Quest

README.md
Popular Screen FX Shader that supports audio link for worlds and avatars.
=> Audio Link Screen FX Shader in the list

AudioLink/Materials/mat_AudioLink.mat, AudioLink/Scenes/AudioLink_ExampleScene.unity, AudioLink/Scenes/AudioLink_ExampleScene/Materials/mat_AudioLinkDocs_Demo9.mat, AudioLink/Scenes/AudioLink_ExampleScene/Materials/mat_AudioLinkDocs_Demo9.mat.meta, AudioLink/Scripts/AudioLink.cs, AudioLink/Shaders/AudioLinkDocs_Demo9.shader, AudioLink/Shaders/AudioLinkDocs_Demo9.shader.meta, AudioLinkSandbox/Scenes/AudioLink_LiveScene.unity
- Fixes theme colors not updating with changes to the AudioLink.cs object.
- Make the feature visible to people browsing the panels.
=> Fix theme color and add a demo panel for it.

AudioLink/Resources/tex_UdonAudioLink.png.meta
Filter mode used to be "Point", now it's "Bilinear".
context: llealloo's suggestion https://discord.com/channels/840894950011043841/840899396216291329/972195518174330890
=> fix pixelated logo on controller

AudioLink/Shaders/AudioLink.shader
Could've maybe converted the specialized implementations to use this but it seems like someone had fun with optimization :)
=> Cleanup repeated uint encoding code.

Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLinkMiniPlayer.cs, Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLinkMiniPlayerController.cs
=> Specify VRC.SDKBase.Utilities.IsValid to avoid possible ambiguity 

Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLink.cs, Packages/com.llealloo.audiolink/Runtime/Shaders/AudioLink.cginc, Packages/com.llealloo.audiolink/Runtime/Shaders/AudioLink.shader
_AdvancedTimeProps2.w is still sampled by AudioLink.shader so we need to look into that
=> removed profiling stuff

AudioLinkUnityProject/Assets/AudioLinkSandbox/Scripts/PortSizeController.cs
Implemented a network time based solution for doing events using manual sync.
=> Changed Networking For PortSizeController

Packages/com.llealloo.audiolink/Runtime/Scripts/YtdlpPlayer.cs
- Removed a duplicate console warning
- Add per-platform warning in inspector that tells you how to resolve the issue.
=> Warning for unsupported or unfound ytdlp

Packages/com.llealloo.audiolink/Runtime/Shaders/Amplify/Functions/AudioLinkTime.asset, README.md
Fixed the Instance Time from the AudioLinkTime node throwing an exception when used.
=> Fixed AudioLinkTime node.

Packages/com.llealloo.audiolink/Editor/Scripts/AudioLinkEditor.cs
make editor work on standalone
add warnings
improve linkall button
restore lost audiodata2D references automatically
=> improve the editor

Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLink.cs
* Used Networking.IsInstanceOwner instead of Networking.LocalPlayer.isInstanceOwner
=> Fixed null ref upon leaving

.github/workflows/iterate.yaml, .github/workflows/release.yaml
• Updated create-unitypackage Actions since they broke due to changes in Node versions.
=> Fixed create-unitypackage Actions

Docs/README.md
Revise Media State docs, so it's not just "Contains:".
=> Revise Media State docs in README.md

.gitignore
=> Add Jetbrains config folder to gitignore.

Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLink.cs
Optional support for dual mono audio
=> Add support for dual mono setups (AVPro)

Packages/com.llealloo.audiolink/Runtime/Scripts/AudioReactivePostProcessing.asset, Packages/com.llealloo.audiolink/Runtime/Scripts/AudioReactivePostProcessing.asset.meta, Packages/com.llealloo.audiolink/Runtime/Scripts/AudioReactivePostProcessing.cs, Packages/com.llealloo.audiolink/Runtime/Scripts/AudioReactivePostProcessing.cs.meta
A small utility script based off `AudioReactiveLight.cs` for post processing volume weighting
=> Add AudioReactivePostProcessing.cs and related files

AudioLinkSandboxProject/.gitignore, AudioLinkSandboxUnityProject/.gitignore, AudioLinkUnityProject/.gitignore, AudioLinkWebProject/.gitignore, Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLink.cs
Hoist some arrays to class fields to avoid excessive array allocations (on behalf of @dooly123).
=> Minor GC improvement

Packages/com.llealloo.audiolink/Runtime/Scripts/ytdlpPlayer.cs
It's not useless! It's very useful for iterating on shaders and stuff.
=> Custom ytdlp for Worlds SDK

Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLink.cs
For some reason, Unity make CRTs update multiple times per frame when multiple views (scene/game/etc) are enabled.
To mitigate this, make the CRT use OnDemand when in editor via compiler `#if`, and use the existing update loop to handle updating the CRT.
Confirmed to work in both VRChat and Standalone projects.
=> Fix crt update speed multiplying when multiple views are active

AudioLinkSandboxUnityProject/ProjectSettings/ProjectSettings.asset, Packages/com.llealloo.audiolink/Runtime/AudioLinkMiniPlayer.prefab, Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLinkController.cs, Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLinkMiniPlayer.cs, Packages/com.llealloo.audiolink/Runtime/Scripts/ytdlpPlayer.cs
As Media Playback API was already exists for a year, I'm wondering why bundled video players didn't implement it.
This PR attempts to fills this gap.
=> Implement Media Playback Reporting API in Bundled Mini Player and YTDLP player

Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLinkEnums.cs, Packages/com.llealloo.audiolink/Runtime/Scripts/AudioLinkEnums.cs.meta, Packages/com.llealloo.audiolink/Runtime/Scripts/AudioReactiveLight.cs
Also add script file for storing useful audiolink enums.
=> Add theme color support to AudioReactiveLight.
